[package]
name = "stunt-router-macro"
version = "0.1.0"
edition = "2024"

description = "Macros for the stunt router"
readme = "../../README.md"
authors = ["proxin"]
repository = "https://github.com/proxin187/stunt"
keywords = ["web", "javascript", "gui", "wasm", "webasm"]
categories = ["gui", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.101"
quote = "1.0.40"
proc-macro2 = "1.0.95"
