[package]
name = "stunt"
version = "0.1.0"
edition = "2024"

description = "A declarative web framework for Rust/Wasm"
readme = "../../README.md"
authors = ["proxin"]
repository = "https://github.com/proxin187/stunt"
keywords = ["web", "javascript", "gui", "wasm", "webasm"]
categories = ["gui", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
stunt-macro = { path = "../stunt-macro", version = "0.1.0" }
spin = "0.10.0"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["Document", "HtmlElement", "Element", "Node", "Text", "Window", "console"] }
itertools = "0.14.0"


